Fix so reset works, plus addition of section resets
co-cddo/cloudmaturity pull request #19
Opened 2024-02-28 23:35 UTC by samjroberts

Original reset didn't clear local storage as was receiving an empty identifier ("model"), so instead updated it so that reset removes the entire cmm model. 

I've also updated the reset at the bottom of each section to use a 'section reset' function, which takes the local storage 'cmm' object, removes the particular section data from it (taken from url), and resets the cmm object with the retrated data. This means the 'hard' reset is only on the first page.

![before-section-reset](https://github.com/co-cddo/cloudmaturity/assets/28672846/b52be736-6fa5-4343-adb1-e0e73948f1a0)
![during-section-reset](https://github.com/co-cddo/cloudmaturity/assets/28672846/8d483f32-da13-49c0-b544-80fb5662be88)
![after-section-reset](https://github.com/co-cddo/cloudmaturity/assets/28672846/8081879c-ff01-43c7-a20c-05fc4251547c)

2024-03-04 16:53 UTC, chrisns requested changes
Hey, Thanks for the PR! ❤️ 
I'm not sure on the use case of resetting just the section, did you have any thoughts on that, as opposed to perhaps just removing the reset button from the question pages?

2024-03-04 16:53 UTC, chrisns commented on src/assets/cmm_assessment.js
> +  const category = href.substring(href.lastIndexOf("/") + 1);
I think i'd prefer you got the section from the questions on the page rather than the current href, since it creates a dependency that doesn't have any test coverage

2024-03-04 16:53 UTC, chrisns commented on src/assets/cmm_assessment.js
> +  // Set the updated data object as the new cmm link
comments seem over verbose
its quite clear what the code is doing?
```suggestion
  const data = JSON.parse(localStorage.getItem(storageItem));
  delete data[category];
```

2024-03-04 18:38 UTC, samjroberts commented on src/assets/cmm_assessment.js
> +  // Set the updated data object as the new cmm link
Ah I commented first as I was figuring out what the data object looked like, and then left it in there! Have removed now :)

2024-03-04 19:10 UTC, samjroberts commented on src/assets/cmm_assessment.js
> +  const category = href.substring(href.lastIndexOf("/") + 1);
Updated so that the section/category is grabbed by `const section = document.querySelectorAll("input")[0].name.split("_")[1];` - good prompt, this is cleaner anyway! See latest commit.

2024-03-04 19:15 UTC, samjroberts commented
> Hey, Thanks for the PR! ❤️

You're welcome!

> I'm not sure on the use case of resetting just the section, did you have any thoughts on that, as opposed to perhaps just removing the reset button from the question pages?

I originally opened the PR just to fix the main reset button, and then realised that I can clear the whole form from a single section - which didn't really make sense to me. Just felt like it might be confusing as you'd hit reset and realise you'd cleared the whole report. Hence the addition. But I'm not wedded to it, it may make more sense to have a different secondary action there, like 'return to home' or 'return to report'.

2024-03-05 08:40 UTC, chrisns requested changes

2024-03-05 08:40 UTC, chrisns commented on src/_includes/nextAssessmentButton.njk
> +<a href="{{ window.location.href }}" id="resetSectionButton" role="button" draggable="false" class="govuk-button govuk-button--warning" data-module="govuk-button">
does `window.location.href` work here?
given that it's all static html and this is rendered

2024-03-05 17:12 UTC, chrisns commented on src/_includes/nextAssessmentButton.njk
> +<a href="{{ window.location.href }}" id="resetSectionButton" role="button" draggable="false" class="govuk-button govuk-button--warning" data-module="govuk-button">
```suggestion
<a href="#" id="resetSectionButton" role="button" draggable="false" class="govuk-button govuk-button--warning" data-module="govuk-button">
```

2024-03-05 19:16 UTC, chrisns commented
thanks! ❤️

2024-03-05 19:17 UTC, merged